services:
  mynotifications.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  mynotifications.api:
    image: mynotifications.api
    container_name: 'api'
    build:
      context: .
      dockerfile: MyNotifications.Api/Dockerfile
    environment:
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@mynotifications.rabbitmq:5672"
    ports:
      - "8080:8080"
    depends_on:
      - mynotifications.rabbitmq

  mynotifications.discordsender:
    image: mynotifications.discordsender
    container_name: 'discordsender'
    build:
      context: .
      dockerfile: MyNotifications.DiscordSender/Dockerfile
    environment:
      DiscordOptions__WebhookUrl: ""
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@mynotifications.rabbitmq:5672"
    depends_on:
      - mynotifications.rabbitmq