services:
  my.notifications.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  my.notifications.api:
    image: my-notifications-api
    container_name: 'api'
    build:
      context: .
      dockerfile: MyNotifications.Api/Dockerfile
    environment:
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@my.notifications.rabbitmq:5672"
    ports:
      - "8080:8080"
    depends_on:
      - my.notifications.rabbitmq

  my.notifications.discord.sender:
    image: my-notifications-discord-sender
    container_name: 'discord_sender'
    build:
      context: .
      dockerfile: MyNotifications.DiscordSender/Dockerfile
    environment:
      DiscordOptions__WebhookUrl: ""
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@my.notifications.rabbitmq:5672"
    depends_on:
      - my.notifications.rabbitmq