services:
  mn.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  mn.database:
    image: postgres:latest
    container_name: 'database'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mn_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mn.database.migrator:
    image: mn-database-migrator
    container_name: 'migrator'
    build:
      context: .
      dockerfile: src/MyNotifications.Database.Migrator/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=mn.database;Port=5432;Database=mn_database;Username=user;Password=password"
    depends_on:
      - mn.database
  
  mn.api:
    image: mn-api
    container_name: 'api'
    build:
      context: .
      dockerfile: src/MyNotifications.Api/Dockerfile
    environment:
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@mn.rabbitmq:5672"
      ConnectionStrings__DefaultConnection: "Host=mn.database;Port=5432;Database=mn_database;Username=user;Password=password"
    ports:
      - "8080:8080"
    depends_on:
      - mn.rabbitmq
      - mn.database

  mn.sender:
    image: mn-sender
    container_name: 'sender'
    build:
      context: .
      dockerfile: src/MyNotifications.Sender/Dockerfile
    environment:
      DiscordOptions__WebhookUrl: "https://discord.com/api/webhooks/1297977254982320129/0WaKVdGjjtEWsudVtZKIZuWBR2YicGlNUCTJggFajamob4riIwNrZ-ME4F05TY9bOyI_"
      RabbitMqOptions__HostUri: "amqp://rabbitmq:rabbitmq@mn.rabbitmq:5672"
      ConnectionStrings__DefaultConnection: "Host=mn.database;Port=5432;Database=mn_database;Username=user;Password=password"
    depends_on:
      - mn.rabbitmq
      - mn.database
        
volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log: